"""
VoiceContract PDF Generator — ReportLab Edition
Generates professional legal PDFs: MSA, Invoice, and locked contracts.
"""

import io
import json
import logging
import math
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, cm
from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable,
)
from reportlab.pdfgen import canvas
from reportlab.lib import colors

logger = logging.getLogger("voicecontract.pdf")

# --- Color Palette ---
PRIMARY = HexColor('#2563EB')
SECONDARY = HexColor('#00C2CC')
TEXT_DARK = HexColor('#0A0A0A')
TEXT_BODY = HexColor('#333333')
TEXT_MUTED = HexColor('#666666')
BG_LIGHT = HexColor('#F8FAFC')
BORDER_LIGHT = HexColor('#E2E8F0')


def _get_styles():
    """Build custom paragraph styles."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle(
        name='DocTitle',
        fontName='Helvetica-Bold',
        fontSize=16,
        leading=20,
        alignment=TA_CENTER,
        textColor=TEXT_DARK,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        name='SectionHeader',
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=TEXT_DARK,
        spaceBefore=14,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        name='BodyText10',
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=TEXT_BODY,
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name='BodyBold',
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=14,
        textColor=TEXT_DARK,
        spaceAfter=4,
    ))
    styles.add(ParagraphStyle(
        name='FooterStyle',
        fontName='Helvetica',
        fontSize=8,
        leading=10,
        alignment=TA_CENTER,
        textColor=TEXT_MUTED,
    ))
    styles.add(ParagraphStyle(
        name='FinancialRight',
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        alignment=TA_RIGHT,
        textColor=TEXT_DARK,
    ))
    styles.add(ParagraphStyle(
        name='InvoiceHeader',
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=28,
        alignment=TA_CENTER,
        textColor=white,
        spaceAfter=8,
    ))
    return styles


def _header_footer(canvas_obj, doc, title="VoiceContract", subtitle=""):
    """Draw header bar and footer on every page."""
    canvas_obj.saveState()
    width, height = A4

    # Header bar
    canvas_obj.setFillColor(PRIMARY)
    canvas_obj.rect(0, height - 50, width, 50, fill=1, stroke=0)
    canvas_obj.setFillColor(white)
    canvas_obj.setFont("Helvetica-Bold", 16)
    canvas_obj.drawString(30, height - 35, "VoiceContract")
    if subtitle:
        canvas_obj.setFont("Helvetica", 9)
        canvas_obj.drawRightString(width - 30, height - 35, subtitle)

    # Footer
    canvas_obj.setFillColor(TEXT_MUTED)
    canvas_obj.setFont("Helvetica", 7)
    canvas_obj.drawCentredString(width / 2, 20, f"Page {doc.page}  •  Generated by VoiceContract AI  •  {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    canvas_obj.restoreState()


def _draw_watermark(canvas_obj, stamp_text: str):
    """Draw a diagonal crypto stamp watermark."""
    canvas_obj.saveState()
    width, height = A4
    canvas_obj.setFillColor(HexColor('#00C2CC'))
    canvas_obj.setFillAlpha(0.06)
    canvas_obj.setFont("Helvetica-Bold", 36)
    canvas_obj.translate(width / 2, height / 2)
    canvas_obj.rotate(45)
    text = f"SECURED: {stamp_text[:40]}"
    canvas_obj.drawCentredString(0, 0, text)
    canvas_obj.restoreState()


def _draw_signature_strokes(canvas_obj, strokes, offset_x, offset_y, box_width=180, box_height=60):
    """Draw biometric signature strokes onto the canvas."""
    canvas_obj.saveState()
    canvas_obj.setStrokeColor(TEXT_DARK)
    canvas_obj.setLineWidth(1.2)

    # Draw signature box border
    canvas_obj.setStrokeColor(SECONDARY)
    canvas_obj.setLineWidth(0.5)
    canvas_obj.rect(offset_x, offset_y - box_height, box_width, box_height, fill=0, stroke=1)

    canvas_obj.setStrokeColor(TEXT_DARK)
    canvas_obj.setLineWidth(1.2)

    for stroke in strokes:
        points = stroke.get("points", [])
        if not points or len(points) < 2:
            continue
        path = canvas_obj.beginPath()
        x0 = offset_x + points[0].get("x", 0) * box_width
        y0 = offset_y - points[0].get("y", 0) * box_height
        path.moveTo(x0, y0)
        for pt in points[1:]:
            x = offset_x + pt.get("x", 0) * box_width
            y = offset_y - pt.get("y", 0) * box_height
            path.lineTo(x, y)
        canvas_obj.drawPath(path, fill=0, stroke=1)

    canvas_obj.restoreState()


def _parse_contract_paragraphs(contract_text: str, styles):
    """Parse contract text into styled ReportLab flowables."""
    flowables = []
    paragraphs = contract_text.replace("\r", "").split("\n")

    for para in paragraphs:
        para = para.strip()
        if not para:
            flowables.append(Spacer(1, 6))
            continue

        # Escape XML special chars for ReportLab Paragraph
        safe = para.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

        # Document Title (all caps, short)
        if para.isupper() and len(para) < 60 and not any(c.isdigit() for c in para):
            flowables.append(Paragraph(safe, styles['DocTitle']))
        # Section Headers (e.g., "1. SCOPE OF SERVICES")
        elif len(para) > 2 and para[0].isdigit() and '.' in para[:4] and para.upper() == para:
            flowables.append(Paragraph(safe, styles['SectionHeader']))
        # Financial totals
        elif any(kw in para for kw in ["Subtotal:", "IGST", "CGST", "SGST", "Grand Total:"]):
            flowables.append(Paragraph(safe, styles['FinancialRight']))
        # Key-Value Pairs
        elif ":" in para and len(para.split(":")[0]) < 25:
            parts = para.split(":", 1)
            formatted = f"<b>{parts[0].replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')}:</b> {parts[1].strip().replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')}"
            flowables.append(Paragraph(formatted, styles['BodyText10']))
        # Standard body text
        else:
            flowables.append(Paragraph(safe, styles['BodyText10']))

    return flowables


# ---------------------------------------------------------------------------
# PUBLIC API
# ---------------------------------------------------------------------------

def generate_locked_pdf(contract_text: str, signature_strokes: list, metadata: dict) -> bytes:
    """
    Generate a locked PDF with single signature (backward-compatible).
    Used by signature.py for provider-signed contracts.
    """
    buffer = io.BytesIO()
    styles = _get_styles()
    crypto_stamp = metadata.get("crypto_stamp", "UNVERIFIED")
    session_id = metadata.get("session_id", "Unknown")

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=65, bottomMargin=40,
        leftMargin=30, rightMargin=30,
        title=f"Secured MSA - {session_id}",
        author="VoiceContract Nexus",
        subject=json.dumps(metadata),
    )

    flowables = _parse_contract_paragraphs(contract_text, styles)

    # Signature section
    flowables.append(Spacer(1, 30))
    flowables.append(HRFlowable(width="100%", thickness=1, color=BORDER_LIGHT, spaceAfter=12))
    flowables.append(Paragraph("EXECUTED &amp; DIGITALLY SIGNED:", styles['SectionHeader']))
    flowables.append(Spacer(1, 8))

    # Placeholder for signature — actual strokes drawn in onPage
    sig_label = Paragraph(
        f"<font size='8' color='#666666'>Biometric Signature — Crypto Stamp: {crypto_stamp[:32]}...</font>",
        styles['BodyText10']
    )
    flowables.append(sig_label)
    flowables.append(Spacer(1, 70))  # Reserve space for signature drawing

    # Metadata footer
    flowables.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_LIGHT, spaceAfter=6))
    ts = metadata.get("timestamp", datetime.utcnow().isoformat())
    flowables.append(Paragraph(
        f"<font size='7' color='#999999'>Session: {session_id} | Timestamp: {ts} | Integrity: SHA-256</font>",
        styles['FooterStyle']
    ))

    # Build with custom header/footer/watermark
    def on_page(c, d):
        _header_footer(c, d, subtitle="Master Service Agreement")
        _draw_watermark(c, crypto_stamp)
        # Draw signature strokes at a fixed position near the bottom
        if signature_strokes:
            page_w, page_h = A4
            _draw_signature_strokes(c, signature_strokes, offset_x=30, offset_y=160, box_width=180, box_height=60)

    doc.build(flowables, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()


def generate_msa_pdf(
    msa_text: str,
    provider_sig: list,
    client_sig: list,
    metadata: dict,
    provider_info: dict | None = None,
    client_info: dict | None = None,
) -> bytes:
    """
    Generate an MSA PDF with dual signature blocks (Provider + Client).
    """
    buffer = io.BytesIO()
    styles = _get_styles()
    crypto_stamp = metadata.get("crypto_stamp", "UNVERIFIED")
    session_id = metadata.get("session_id", "Unknown")
    prov = provider_info or {}
    cli = client_info or {}

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=65, bottomMargin=40,
        leftMargin=30, rightMargin=30,
        title=f"MSA - {session_id}",
        author="VoiceContract Nexus",
        subject=json.dumps(metadata),
    )

    flowables = _parse_contract_paragraphs(msa_text, styles)

    # Party information table
    flowables.append(Spacer(1, 20))
    flowables.append(HRFlowable(width="100%", thickness=1, color=BORDER_LIGHT, spaceAfter=12))

    party_data = [
        [
            Paragraph("<b>SERVICE PROVIDER</b>", styles['BodyBold']),
            Paragraph("<b>CLIENT</b>", styles['BodyBold']),
        ],
        [
            Paragraph(f"{prov.get('company_name', 'Provider')}<br/>{prov.get('address', '')}<br/>GST: {prov.get('gst_number', 'N/A')}", styles['BodyText10']),
            Paragraph(f"{cli.get('client_name', 'Client')}<br/>{cli.get('client_company', '')}<br/>{cli.get('client_address', '')}<br/>{cli.get('client_email', '')}", styles['BodyText10']),
        ]
    ]
    party_table = Table(party_data, colWidths=[250, 250])
    party_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, 0), 1, BORDER_LIGHT),
    ]))
    flowables.append(party_table)

    # Dual signature section
    flowables.append(Spacer(1, 24))
    flowables.append(Paragraph("EXECUTED &amp; DIGITALLY SIGNED BY BOTH PARTIES:", styles['SectionHeader']))
    flowables.append(Spacer(1, 8))

    sig_data = [
        [
            Paragraph("<b>Provider Signature</b>", styles['BodyBold']),
            Paragraph("<b>Client Signature</b>", styles['BodyBold']),
        ],
        [
            Paragraph("<font size='7' color='#999'>Biometric signature below</font>", styles['BodyText10']),
            Paragraph("<font size='7' color='#999'>Biometric signature below</font>", styles['BodyText10']),
        ]
    ]
    sig_table = Table(sig_data, colWidths=[250, 250])
    sig_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    flowables.append(sig_table)
    flowables.append(Spacer(1, 80))  # Reserve space for signature drawings

    # Metadata
    flowables.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_LIGHT, spaceAfter=6))
    flowables.append(Paragraph(
        f"<font size='7' color='#999999'>Crypto Stamp: {crypto_stamp} | Session: {session_id}</font>",
        styles['FooterStyle']
    ))

    def on_page(c, d):
        _header_footer(c, d, subtitle="Master Service Agreement")
        _draw_watermark(c, crypto_stamp)
        # Draw dual signatures
        if provider_sig:
            _draw_signature_strokes(c, provider_sig, offset_x=30, offset_y=170, box_width=180, box_height=60)
        if client_sig:
            _draw_signature_strokes(c, client_sig, offset_x=310, offset_y=170, box_width=180, box_height=60)

    doc.build(flowables, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()


def generate_invoice_pdf(
    invoice_data: dict,
    metadata: dict,
    provider_info: dict | None = None,
    client_info: dict | None = None,
) -> bytes:
    """
    Generate a professional GST Tax Invoice PDF.
    
    invoice_data keys:
        invoice_number, date, due_date, items (list of dicts),
        subtotal, tax_rate, tax_amount, grand_total,
        bank_details (dict with bank_name, account_number, ifsc, branch)
    """
    buffer = io.BytesIO()
    styles = _get_styles()
    prov = provider_info or {}
    cli = client_info or {}
    session_id = metadata.get("session_id", "Unknown")

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=65, bottomMargin=40,
        leftMargin=30, rightMargin=30,
        title=f"Tax Invoice - {invoice_data.get('invoice_number', 'N/A')}",
        author="VoiceContract Nexus",
    )

    flowables = []

    # Invoice header
    flowables.append(Paragraph("TAX INVOICE", styles['DocTitle']))
    flowables.append(Spacer(1, 4))
    flowables.append(HRFlowable(width="100%", thickness=2, color=PRIMARY, spaceAfter=16))

    # Invoice meta info
    inv_meta = [
        [
            Paragraph(f"<b>Invoice #:</b> {invoice_data.get('invoice_number', 'N/A')}", styles['BodyText10']),
            Paragraph(f"<b>Date:</b> {invoice_data.get('date', datetime.utcnow().strftime('%B %d, %Y'))}", styles['BodyText10']),
        ],
        [
            Paragraph(f"<b>Due Date:</b> {invoice_data.get('due_date', 'On Receipt')}", styles['BodyText10']),
            Paragraph("", styles['BodyText10']),
        ],
    ]
    meta_table = Table(inv_meta, colWidths=[270, 250])
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    flowables.append(meta_table)
    flowables.append(Spacer(1, 16))

    # From / To blocks
    from_to = [
        [
            Paragraph("<b>FROM (Service Provider)</b>", styles['BodyBold']),
            Paragraph("<b>TO (Client)</b>", styles['BodyBold']),
        ],
        [
            Paragraph(
                f"{prov.get('company_name', 'Provider')}<br/>"
                f"{prov.get('address', '')}<br/>"
                f"GST: {prov.get('gst_number', 'N/A')}",
                styles['BodyText10']
            ),
            Paragraph(
                f"{cli.get('client_name', 'Client')}<br/>"
                f"{cli.get('client_company', '')}<br/>"
                f"{cli.get('client_address', '')}<br/>"
                f"{cli.get('client_email', '')}",
                styles['BodyText10']
            ),
        ]
    ]
    from_to_table = Table(from_to, colWidths=[270, 250])
    from_to_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, 0), 1, PRIMARY),
        ('BACKGROUND', (0, 0), (-1, 0), HexColor('#F0F4FF')),
    ]))
    flowables.append(from_to_table)
    flowables.append(Spacer(1, 20))

    # Items table
    items = invoice_data.get("items", [])
    header_row = [
        Paragraph("<b>Description</b>", styles['BodyBold']),
        Paragraph("<b>HSN/SAC</b>", styles['BodyBold']),
        Paragraph("<b>Qty</b>", styles['BodyBold']),
        Paragraph("<b>Rate (₹)</b>", styles['BodyBold']),
        Paragraph("<b>Amount (₹)</b>", styles['BodyBold']),
    ]
    table_data = [header_row]

    for item in items:
        row = [
            Paragraph(str(item.get("description", "Professional Services")), styles['BodyText10']),
            Paragraph(str(item.get("hsn_sac", "99831")), styles['BodyText10']),
            Paragraph(str(item.get("qty", 1)), styles['BodyText10']),
            Paragraph(f"₹{item.get('rate', item.get('amount', 0)):,.2f}", styles['BodyText10']),
            Paragraph(f"₹{item.get('amount', 0):,.2f}", styles['BodyText10']),
        ]
        table_data.append(row)

    items_table = Table(table_data, colWidths=[180, 60, 40, 90, 100])
    items_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), PRIMARY),
        ('TEXTCOLOR', (0, 0), (-1, 0), white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 8),
        ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
        ('ALIGN', (-1, 0), (-1, -1), 'RIGHT'),
        ('ALIGN', (-2, 0), (-2, -1), 'RIGHT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [white, BG_LIGHT]),
        ('TOPPADDING', (0, 1), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
    ]))
    flowables.append(items_table)
    flowables.append(Spacer(1, 16))

    # Tax calculations
    subtotal = invoice_data.get("subtotal", 0)
    tax_rate = invoice_data.get("tax_rate", 18)
    tax_amount = invoice_data.get("tax_amount", round(subtotal * 0.18, 2))
    grand_total = invoice_data.get("grand_total", round(subtotal + tax_amount, 2))

    # Determine tax type (inter-state vs intra-state)
    is_interstate = invoice_data.get("interstate", True)

    tax_rows = [
        ["", "", "", Paragraph("<b>Subtotal</b>", styles['BodyBold']), Paragraph(f"<b>₹{subtotal:,.2f}</b>", styles['FinancialRight'])],
    ]
    if is_interstate:
        tax_rows.append(
            ["", "", "", Paragraph(f"IGST@{tax_rate}%", styles['BodyText10']), Paragraph(f"₹{tax_amount:,.2f}", styles['FinancialRight'])]
        )
    else:
        half_tax = round(tax_amount / 2, 2)
        half_rate = round(tax_rate / 2, 1)
        tax_rows.append(
            ["", "", "", Paragraph(f"CGST@{half_rate}%", styles['BodyText10']), Paragraph(f"₹{half_tax:,.2f}", styles['FinancialRight'])]
        )
        tax_rows.append(
            ["", "", "", Paragraph(f"SGST@{half_rate}%", styles['BodyText10']), Paragraph(f"₹{half_tax:,.2f}", styles['FinancialRight'])]
        )
    tax_rows.append(
        ["", "", "", Paragraph("<b>Grand Total</b>", styles['BodyBold']), Paragraph(f"<b>₹{grand_total:,.2f}</b>", styles['FinancialRight'])]
    )

    tax_table = Table(tax_rows, colWidths=[180, 60, 40, 90, 100])
    tax_table.setStyle(TableStyle([
        ('ALIGN', (-1, 0), (-1, -1), 'RIGHT'),
        ('ALIGN', (-2, 0), (-2, -1), 'RIGHT'),
        ('LINEABOVE', (-2, -1), (-1, -1), 1.5, PRIMARY),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    flowables.append(tax_table)
    flowables.append(Spacer(1, 24))

    # Bank details
    bank = invoice_data.get("bank_details", {})
    if bank:
        flowables.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_LIGHT, spaceAfter=10))
        flowables.append(Paragraph("<b>Bank Details for Payment</b>", styles['SectionHeader']))
        bank_info = (
            f"Bank: {bank.get('bank_name', 'N/A')}<br/>"
            f"Account Number: {bank.get('account_number', 'N/A')}<br/>"
            f"IFSC Code: {bank.get('ifsc', 'N/A')}<br/>"
            f"Branch: {bank.get('branch', 'N/A')}"
        )
        flowables.append(Paragraph(bank_info, styles['BodyText10']))

    # Footer
    flowables.append(Spacer(1, 30))
    flowables.append(HRFlowable(width="100%", thickness=0.5, color=BORDER_LIGHT, spaceAfter=8))
    flowables.append(Paragraph(
        "<font size='8' color='#999999'>Generated by VoiceContract AI  •  Powered by Antarik Technologies</font>",
        styles['FooterStyle']
    ))

    def on_page(c, d):
        _header_footer(c, d, subtitle="Tax Invoice")

    doc.build(flowables, onFirstPage=on_page, onLaterPages=on_page)
    return buffer.getvalue()
