"use client";

import { useEffect, useState, useRef } from "react";
import { useParams, useRouter } from "next/navigation";
import { motion } from "framer-motion";
import SuccessHandshake from "@/components/animations/SuccessHandshake";

export default function SignaturePortal() {
  const { session_id } = useParams();
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [signed, setSigned] = useState(false);
  const [documents, setDocuments] = useState<any>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [isDrawing, setIsDrawing] = useState(false);

  useEffect(() => {
    // Simulate fetching the document
    setTimeout(() => {
      setDocuments({
        msa: "MASTER SERVICE AGREEMENT\n\nThis agreement is made between Antarik Systems and Acme Corp...\n\n1. SCOPE OF SERVICES: The Provider shall deliver a high-fidelity 3D website architecture.\n2. CONSIDERATION: Total value of 50,000 INR.\n3. TIMELINE: Delivery within 14 business days.\n4. INTELLECTUAL PROPERTY: All rights transfer upon final payment.",
        crypto_stamp: "sha256:7f83b123...9021"
      });
      setLoading(false);
    }, 1500);
  }, [session_id]);

  const startDrawing = (e: any) => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    ctx.beginPath();
    const rect = canvas.getBoundingClientRect();
    const x = (e.clientX || e.touches?.[0].clientX) - rect.left;
    const y = (e.clientY || e.touches?.[0].clientY) - rect.top;
    ctx.moveTo(x, y);
    setIsDrawing(true);
  };

  const draw = (e: any) => {
    if (!isDrawing) return;
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    const rect = canvas.getBoundingClientRect();
    const x = (e.clientX || e.touches?.[0].clientX) - rect.left;
    const y = (e.clientY || e.touches?.[0].clientY) - rect.top;
    ctx.lineTo(x, y);
    ctx.strokeStyle = "#2563EB"; // Corporate blue ink
    ctx.lineWidth = 3;
    ctx.lineCap = "round";
    ctx.stroke();
  };

  const stopDrawing = () => setIsDrawing(false);

  const handleSign = () => {
    setSigned(true);
    // Simulate trigger download
    setTimeout(() => {
      console.log("Downloading document...");
    }, 1000);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex flex-col items-center justify-center text-text premium-noise gap-6">
        <div className="w-12 h-12 border-4 border-primary/20 border-t-primary rounded-full animate-spin" />
        <span className="font-medium text-text-muted">Unlocking document vault...</span>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background text-text font-sans p-8 md:p-16 flex flex-col items-center premium-noise overflow-y-auto">
      
      <div className="w-full max-w-4xl space-y-12 z-10">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between border-b border-border pb-8 gap-4">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-primary/10 text-primary rounded-full text-xs font-semibold mb-4">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8V7a4 4 0 00-8 0v4h8z" /></svg>
              Execution Required
            </div>
            <h1 className="text-4xl font-extrabold tracking-tight">Master Service Agreement</h1>
          </div>
          <div className="text-left md:text-right">
            <span className="text-xs text-text-muted font-medium uppercase tracking-wider block mb-1">Document Hash</span>
            <span className="font-system text-sm font-semibold">{String(session_id).slice(0,12)}...</span>
          </div>
        </div>

        {/* Paper Document Viewer */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-surface border border-border rounded-2xl p-12 shadow-apple-lg relative overflow-hidden"
        >
           {/* Subtle paper texture over the content */}
           <div className="absolute inset-0 bg-[url('/paper.svg')] opacity-50 pointer-events-none mix-blend-multiply" />
           
           <div className="relative z-10">
             <div className="prose prose-slate max-w-none">
                <pre className="whitespace-pre-wrap font-sans text-base text-text leading-relaxed tracking-tight bg-transparent">
                  {documents?.msa}
                </pre>
             </div>

             <div className="mt-20 pt-8 border-t border-border flex justify-between items-center text-xs font-semibold text-text-muted uppercase tracking-wider">
               <span>Generated by VoiceContract AI</span>
               <span>STAMP: {documents?.crypto_stamp?.slice(0,16)}</span>
             </div>
           </div>
        </motion.div>

        {/* Execution Block */}
        {!signed ? (
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="bg-surface border border-border rounded-3xl p-10 shadow-apple flex flex-col md:flex-row gap-12 items-center"
          >
            <div className="flex-1 space-y-4">
              <h3 className="text-2xl font-bold tracking-tight">Digital Affirmation</h3>
              <p className="text-text-muted leading-relaxed">
                By applying your signature, you execute a legally binding agreement synchronized with meeting session {session_id?.slice(0,6)}.
              </p>
            </div>
            
            <div className="flex-1 w-full space-y-6">
               <div className="h-48 bg-background border border-border rounded-2xl relative shadow-apple-inner overflow-hidden cursor-crosshair">
                  <canvas 
                    ref={canvasRef}
                    width={500}
                    height={200}
                    className="w-full h-full"
                    onMouseDown={startDrawing}
                    onMouseMove={draw}
                    onMouseUp={stopDrawing}
                    onMouseLeave={stopDrawing}
                    onTouchStart={startDrawing}
                    onTouchMove={draw}
                    onTouchEnd={stopDrawing}
                  />
                  <div className="absolute bottom-4 right-4 text-xs font-semibold text-text-muted pointer-events-none">Sign Here</div>
               </div>
               <button 
                 onClick={handleSign}
                 className="w-full py-4 bg-text text-white font-semibold rounded-xl shadow-apple hover:bg-black transition-colors hover:-translate-y-0.5 active:scale-95"
               >
                 Execute Contract
               </button>
            </div>
          </motion.div>
        ) : (
          <div className="py-12 flex flex-col items-center">
            <SuccessHandshake />
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1 }}
              className="mt-8 flex gap-4"
            >
              <button 
                onClick={() => router.push('/dashboard')}
                className="px-6 py-3 bg-surface border border-border text-text font-semibold rounded-xl shadow-sm hover:bg-background transition-colors"
              >
                Return to Dashboard
              </button>
            </motion.div>
          </div>
        )}
      </div>
    </div>
  );
}
