from fpdf import FPDF
from datetime import datetime
import base64
import io
from PIL import Image

class ContractPDF(FPDF):
    def header(self):
        # We'll handle the header in the create_pdf function for more control
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(122, 139, 166) # Dusk color
        self.cell(0, 10, f"Generated by VoiceContract — Where your brand lives online. | Confidential | Page {self.page_no()}/{{nb}}", align="C")

def create_pdf(contract_text: str, company_details: dict) -> bytes:
    """
    Takes plain text contract and company details and generates PDF bytes using fpdf2.
    Pure Python implementation, no external binary needed.
    """
    pdf = ContractPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    
    # 1. HEADER SECTION
    # Brand Line (Cyan)
    pdf.set_draw_color(0, 194, 204) # Signal Cyan
    pdf.set_line_width(0.8)
    pdf.line(20, 35, 190, 35)

    # Logo handling
    if company_details.get('logo'):
        try:
            # Extract base64 data
            header, encoded = company_details.get('logo').split(",", 1)
            img_data = base64.b64decode(encoded)
            img = Image.open(io.BytesIO(img_data))
            # Save to a temporary buffer as PNG
            img_buf = io.BytesIO()
            img.save(img_buf, format='PNG')
            img_buf.seek(0)
            pdf.image(img_buf, x=20, y=10, h=20)
        except Exception as e:
            print(f"Logo Processing Error: {e}")

    # Company Info (Right Aligned)
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(102, 102, 102)
    pdf.set_xy(100, 12)
    pdf.cell(90, 5, f"Date: {datetime.now().strftime('%B %d, %Y')}", align="R", ln=True)
    pdf.set_x(100)
    pdf.cell(90, 5, f"GST: {company_details.get('gst_number', 'N/A')}", align="R", ln=True)
    pdf.set_x(100)
    pdf.set_font("helvetica", "", 8)
    pdf.multi_cell(90, 4, company_details.get('address', ''), align="R")

    # Title
    pdf.set_xy(20, 38)
    pdf.set_font("helvetica", "B", 16)
    pdf.set_text_color(0, 194, 204) # Signal Cyan
    pdf.cell(0, 10, company_details.get('company_name', 'Service Provider').upper(), ln=True)
    
    pdf.set_font("helvetica", "BI", 20)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 12, "SERVICE AGREEMENT", ln=True)
    pdf.ln(5)

    # 2. BODY CONTENT
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(51, 51, 51)
    
    lines = contract_text.split("\n")
    for line in lines:
        line = line.strip()
        if not line:
            pdf.ln(4)
            continue
            
        # If line looks like a heading (e.g., "1. PARTIES" or "PAYMENT TERMS")
        if (line.isupper() and len(line) < 50) or (line[0:1].isdigit() and "." in line[0:4] and line.split(".")[1].strip().isupper()):
            pdf.ln(4)
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(0, 194, 204) # Signal Cyan
            pdf.cell(0, 8, line, ln=True)
            pdf.set_font("helvetica", "", 11)
            pdf.set_text_color(51, 51, 51)
        else:
            pdf.multi_cell(0, 6, line, align="J")
            pdf.ln(2)

    # 3. SIGNATURE SECTION
    if pdf.get_y() > 230: # Ensure signature isn't cut off
        pdf.add_page()
    
    pdf.ln(20)
    y_sig = pdf.get_y()
    pdf.set_draw_color(180, 180, 180)
    pdf.set_line_width(0.2)
    
    # Provider Line
    pdf.line(20, y_sig + 15, 85, y_sig + 15)
    pdf.set_font("helvetica", "B", 8)
    pdf.set_xy(20, y_sig + 17)
    pdf.cell(65, 5, company_details.get('your_name', 'Authorised Signatory'))
    pdf.set_xy(20, y_sig + 21)
    pdf.set_font("helvetica", "", 7)
    pdf.cell(65, 5, "For " + company_details.get('company_name', 'Service Provider'))

    # Client Line
    pdf.line(125, y_sig + 15, 190, y_sig + 15)
    pdf.set_font("helvetica", "B", 8)
    pdf.set_xy(125, y_sig + 17)
    pdf.cell(65, 5, "Client Signatory")
    pdf.set_xy(125, y_sig + 21)
    pdf.set_font("helvetica", "", 7)
    pdf.cell(65, 5, "Authorised Signatory")

    return bytes(pdf.output())
