from dataclasses import dataclass
from datetime import datetime
import base64
import io

from fpdf import FPDF
from PIL import Image


UNICODE_REPLACEMENTS = {
    "₹": "INR ",
    "—": "-",
    "–": "-",
    "…": "...",
    "’": "'",
    "‘": "'",
    "´": "'",
    "“": '"',
    "”": '"',
}


@dataclass(frozen=True)
class GeneratedDocument:
    content: bytes
    media_type: str
    file_extension: str


def sanitize_for_pdf(text: str) -> str:
    """
    Convert common Unicode punctuation/currency to Helvetica-safe Latin-1.
    Any remaining unsupported glyph is replaced with '?' as a final guard.
    """
    if text is None:
        text = ""
    elif not isinstance(text, str):
        text = str(text)

    for unsupported, replacement in UNICODE_REPLACEMENTS.items():
        text = text.replace(unsupported, replacement)

    return text.encode("latin-1", "replace").decode("latin-1")


def _company_value(company_details: dict, key: str, default: str = "") -> str:
    return sanitize_for_pdf(company_details.get(key, default))


class ContractPDF(FPDF):
    def header(self):
        # Header is handled in create_pdf for precise brand layout control.
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(122, 139, 166)  # Dusk color
        footer_text = (
            f"Generated by VoiceContract - Where your brand lives online. "
            f"| Confidential | Page {self.page_no()}/{{nb}}"
        )
        self.cell(0, 10, sanitize_for_pdf(footer_text), align="C")


def create_pdf(contract_text: str, company_details: dict) -> bytes:
    """
    Takes plain text contract and company details and generates PDF bytes using fpdf2.
    Pure Python implementation, no external binary needed.
    """
    raw_contract_text = contract_text or ""
    contract_text = sanitize_for_pdf(contract_text)

    pdf = ContractPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # 1. HEADER SECTION
    # Brand Line (Cyan)
    pdf.set_draw_color(0, 194, 204)  # Signal Cyan
    pdf.set_line_width(0.8)
    pdf.line(20, 35, 190, 35)

    # Logo handling
    if company_details.get("logo"):
        try:
            _, encoded = company_details.get("logo").split(",", 1)
            img_data = base64.b64decode(encoded)
            img = Image.open(io.BytesIO(img_data))
            img_buf = io.BytesIO()
            img.save(img_buf, format="PNG")
            img_buf.seek(0)
            pdf.image(img_buf, x=20, y=10, h=20)
        except Exception as e:
            print(f"Logo Processing Error: {e}")

    # Company Info (Right Aligned)
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(102, 102, 102)
    pdf.set_xy(100, 12)
    pdf.cell(90, 5, sanitize_for_pdf(f"Date: {datetime.now().strftime('%B %d, %Y')}"), align="R", ln=True)
    pdf.set_x(100)
    pdf.cell(90, 5, sanitize_for_pdf(f"GST: {_company_value(company_details, 'gst_number', 'N/A')}"), align="R", ln=True)
    pdf.set_x(100)
    pdf.set_font("helvetica", "", 8)
    pdf.multi_cell(90, 4, _company_value(company_details, "address"), align="R")

    # Title
    pdf.set_xy(20, 38)
    pdf.set_font("helvetica", "B", 16)
    pdf.set_text_color(0, 194, 204)  # Signal Cyan
    company_name = _company_value(company_details, "company_name", "Service Provider").upper()
    pdf.cell(0, 10, company_name, ln=True)

    pdf.set_font("helvetica", "BI", 20)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 12, sanitize_for_pdf("SERVICE AGREEMENT"), ln=True)
    pdf.ln(5)

    # 2. BODY CONTENT
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(51, 51, 51)

    lines = contract_text.split("\n")
    for line in lines:
        line = sanitize_for_pdf(line.strip())
        if not line:
            pdf.ln(4)
            continue

        is_numbered_heading = (
            line[0:1].isdigit()
            and "." in line[0:4]
            and len(line.split(".", 1)) > 1
            and line.split(".", 1)[1].strip().isupper()
        )

        # If line looks like a heading (e.g., "1. PARTIES" or "PAYMENT TERMS")
        if (line.isupper() and len(line) < 50) or is_numbered_heading:
            pdf.ln(4)
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(0, 194, 204)  # Signal Cyan
            pdf.cell(0, 8, line, ln=True)
            pdf.set_font("helvetica", "", 11)
            pdf.set_text_color(51, 51, 51)
        else:
            pdf.multi_cell(0, 6, line, align="J")
            pdf.ln(2)

    # 3. SIGNATURE SECTION
    if pdf.get_y() > 230:
        pdf.add_page()

    pdf.ln(20)
    y_sig = pdf.get_y()
    pdf.set_draw_color(180, 180, 180)
    pdf.set_line_width(0.2)

    # Provider Line
    pdf.line(20, y_sig + 15, 85, y_sig + 15)
    pdf.set_font("helvetica", "B", 8)
    pdf.set_xy(20, y_sig + 17)
    pdf.cell(65, 5, _company_value(company_details, "your_name", "Authorised Signatory"))
    pdf.set_xy(20, y_sig + 21)
    pdf.set_font("helvetica", "", 7)
    pdf.cell(65, 5, sanitize_for_pdf("For " + _company_value(company_details, "company_name", "Service Provider")))

    # Client Line
    pdf.line(125, y_sig + 15, 190, y_sig + 15)
    pdf.set_font("helvetica", "B", 8)
    pdf.set_xy(125, y_sig + 17)
    pdf.cell(65, 5, sanitize_for_pdf("Client Signatory"))
    pdf.set_xy(125, y_sig + 21)
    pdf.set_font("helvetica", "", 7)
    pdf.cell(65, 5, sanitize_for_pdf("Authorised Signatory"))

    try:
        return bytes(pdf.output())
    except Exception as e:
        print(f"PDF Output Error: {e}")
        return raw_contract_text.encode("utf-8", "replace")


def create_document(contract_text: str, company_details: dict) -> GeneratedDocument:
    """
    Generates a PDF when possible, otherwise returns the raw contract as text.
    This keeps the API on a 200 response path during live demos.
    """
    try:
        content = create_pdf(contract_text, company_details)
        is_pdf = content.startswith(b"%PDF")
        return GeneratedDocument(
            content=content,
            media_type="application/pdf" if is_pdf else "text/plain; charset=utf-8",
            file_extension="pdf" if is_pdf else "txt",
        )
    except Exception as e:
        print(f"PDF Generation Error: {e}")
        return GeneratedDocument(
            content=(contract_text or "").encode("utf-8", "replace"),
            media_type="text/plain; charset=utf-8",
            file_extension="txt",
        )
