import pdfkit
from datetime import datetime

def create_pdf(contract_text: str, company_details: dict) -> bytes:
    """
    Takes plain text contract and company details, formats as HTML, 
    and generates PDF bytes using pdfkit.
    """
    
    logo_html = ""
    if company_details.get('logo'):
        logo_html = f'<img src="{company_details.get("logo")}" style="max-height: 80px; margin-bottom: 20px;">'

    # Very basic markdown-to-html conversion for sections
    html_body = contract_text.replace("\n\n", "</p><p>").replace("\n", "<br>")
    
    # We apply strong CSS styling for a professional look
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: 'Helvetica', 'Arial', sans-serif; line-height: 1.6; margin: 40px; color: #333; }}
            .header {{ text-align: left; border-bottom: 2px solid #00C2CC; padding-bottom: 20px; margin-bottom: 30px; }}
            .header h1 {{ margin: 5px 0 0 0; color: #111; font-style: italic; font-size: 28px; }}
            .company-info {{ float: right; text-align: right; font-size: 12px; color: #666; }}
            .company-name {{ font-size: 20px; font-weight: bold; color: #00C2CC; margin-bottom: 5px; }}
            .footer {{ position: fixed; bottom: 20px; width: 100%; font-size: 10px; color: #888; border-top: 1px solid #eee; padding-top: 10px; text-align: center; }}
            p {{ margin-bottom: 15px; text-align: justify; }}
            strong {{ color: #111; }}
            .content h3 {{ color: #00C2CC; border-bottom: 1px solid #eee; padding-bottom: 5px; margin-top: 25px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <div class="company-info">
                <div>Date: {datetime.now().strftime('%B %d, %Y')}</div>
                <div>GST: {company_details.get('gst_number', 'N/A')}</div>
                <div>{company_details.get('address', '')}</div>
            </div>
            {logo_html}
            <div class="company-name">{company_details.get('company_name', 'Service Provider').upper()}</div>
            <h1>SERVICE AGREEMENT</h1>
        </div>
        
        <div class="content">
            <p>{html_body}</p>
        </div>
        
        <div class="footer">
            Generated by VoiceContract — Where your brand lives online. | Confidential
        </div>
    </body>
    </html>
    """

    options = {
        'page-size': 'A4',
        'margin-top': '0.75in',
        'margin-right': '0.75in',
        'margin-bottom': '1.0in',
        'margin-left': '0.75in',
        'encoding': "UTF-8",
        'no-outline': None,
        'enable-local-file-access': None
    }

    try:
        # Assuming wkhtmltopdf is installed on the system
        pdf_bytes = pdfkit.from_string(html_content, False, options=options)
        return pdf_bytes
    except Exception as e:
        print(f"PDF Generation Error: {str(e)}")
        raise e
